var AbstractCommand = require('../../../../lib/base/AbstractCommand'),
	fs = require('fs');

class VeryLongCommand extends AbstractCommand {
	constructor() {
		super();
	}

	get name() {
		return 'veryLong';
	}

	handle(message) {
		if (this.userOnCooldown(message.author.id, 60000))
			return this.sendMessage(message, 'You can only use this command once every minute.', { deleteAfter: 4000, deleteTrigger: true });
		this.sendMessage(message, `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus accumsan condimentum gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam pellentesque, turpis nec commodo elementum, est diam maximus sem, quis congue massa leo vitae mauris. Sed velit dui, efficitur nec fermentum id, sollicitudin non leo. Quisque eget nisl malesuada, condimentum turpis pulvinar, auctor dolor. Maecenas efficitur facilisis mi, sed ullamcorper quam pulvinar sed. Maecenas id sapien venenatis, pretium nisi sit amet, faucibus massa.

Donec ultrices urna non enim lacinia congue. Curabitur consectetur scelerisque erat ac tincidunt. Phasellus bibendum enim at erat lacinia, id placerat lorem tincidunt. Suspendisse potenti. In posuere, tellus eget condimentum maximus, purus magna tincidunt leo, at pretium tellus sapien vitae odio. Cras lacus nunc, blandit id auctor a, vestibulum at augue. Cras vel ipsum placerat, fermentum tellus ornare, tincidunt tellus. Pellentesque hendrerit nunc et blandit viverra. Suspendisse vel turpis placerat, efficitur nisi vel, auctor est. Aenean aliquet maximus auctor. Donec accumsan nibh in turpis condimentum ornare.

Praesent ex nibh, feugiat nec sollicitudin vitae, imperdiet viverra augue. Praesent venenatis dolor ut quam finibus ultrices. Praesent imperdiet augue ultricies leo accumsan eleifend. Nam a leo nec nulla blandit porta. Proin nec tempus metus. Donec malesuada lectus interdum tellus finibus faucibus. In enim dui, iaculis varius blandit et, blandit at nisl. Pellentesque non iaculis enim. Fusce at consectetur metus, eget aliquet metus. Ut mollis enim nunc, sit amet semper felis aliquet quis. Pellentesque lobortis dui in dignissim aliquam. Vestibulum rutrum posuere aliquet. Morbi placerat maximus turpis.

Vestibulum purus lectus, placerat vitae eros eget, rutrum ornare ante. Vivamus quis nibh ipsum. Nunc tincidunt erat magna, vel fringilla est mattis in. Nunc consectetur lacus quis dictum porta. Sed ut tincidunt lectus, at molestie velit. Maecenas tempor pulvinar velit sit amet ornare. Nulla ornare turpis vel odio dignissim convallis a semper arcu. Nullam erat nunc, vulputate eu accumsan ac, pellentesque quis purus. Phasellus pharetra blandit arcu, nec rutrum metus consectetur quis. Sed lacinia elit sit amet ante pellentesque, vel vestibulum quam dictum. Nulla accumsan quis neque eget elementum. Integer at dignissim nunc. Quisque suscipit nisi sit amet suscipit rutrum. Cras tempus, arcu sed cursus iaculis, turpis nibh accumsan augue, et vulputate purus neque id felis. Donec vel ante odio.

Nunc leo tellus, ullamcorper nec tortor vel, eleifend viverra arcu. Sed tincidunt a neque a facilisis. Donec accumsan quam orci, vitae consequat libero tempor sed. Donec facilisis vitae magna vitae maximus. In hac habitasse platea dictumst. Proin convallis, eros in fringilla commodo, mi neque iaculis enim, vitae efficitur turpis velit ut tellus. Aliquam id neque vel nibh fermentum aliquet non at nulla. Praesent accumsan mauris eget convallis pretium. Praesent tincidunt magna vel elementum congue. Pellentesque massa ante, consequat quis magna eu, convallis rhoncus est. Pellentesque mattis aliquet lorem, non tincidunt lectus dictum sit amet. Quisque tincidunt risus nec elit efficitur, in vehicula arcu sodales. Sed in suscipit enim. Duis porta eros a dignissim condimentum. Suspendisse placerat dictum leo, sed ultricies ligula sodales et.

Integer vitae ultricies libero. Ut interdum sagittis maximus. Etiam nec pharetra dui. Vivamus vestibulum magna a bibendum sodales. Vivamus eu facilisis nibh. Proin molestie ante auctor, aliquet nunc eu, hendrerit tortor. Aliquam erat volutpat. Maecenas posuere varius ligula in posuere. Suspendisse maximus elit ut libero hendrerit viverra. Nulla vitae felis non arcu mollis rhoncus. Cras eu ullamcorper quam, eget consectetur nunc. Maecenas aliquam hendrerit enim, sit amet aliquet urna tempus sodales. Aenean nisl diam, eleifend ac congue eget, elementum euismod risus. Nullam fringilla eget enim vitae euismod. Quisque iaculis nunc et dolor congue volutpat.

Donec accumsan felis ut tellus ullamcorper venenatis. Suspendisse efficitur laoreet tellus, et porta risus. Quisque a vulputate libero, nec sollicitudin urna. Cras aliquet dolor quam, at gravida lacus gravida at. Curabitur ultrices felis in mauris molestie pharetra. Donec pretium ligula lectus, non dapibus lectus vulputate ut. Nullam et urna congue, fringilla sem ut, vehicula dui. Nulla eget nulla eu arcu ultricies euismod eu ac mi. Sed a quam bibendum, finibus lorem at, gravida ligula. Morbi a magna in tellus sollicitudin efficitur eu sed mi. Donec pretium, purus at auctor bibendum, metus magna cursus felis, quis venenatis ex nulla nec nunc. Praesent quis interdum nibh. Curabitur non sodales justo, eu posuere arcu. Fusce vestibulum, eros eu lobortis scelerisque, magna risus fringilla libero, vitae dapibus eros velit et turpis. Praesent ligula ante, molestie vel aliquam in, posuere vel nisi. Nullam pulvinar faucibus tortor, in condimentum velit finibus id.

Praesent gravida sapien enim, a volutpat velit tincidunt quis. Mauris vel nibh ac lectus sollicitudin efficitur. Donec in ligula elit. Morbi consequat tempor pellentesque. Suspendisse quam velit, dictum non imperdiet eu, pretium vel lacus. Nunc eget ultricies ipsum. In vitae sollicitudin sem. Sed tellus nisl, gravida eget tempor eget, interdum sed leo. Integer consectetur nunc eu nisi gravida laoreet. Curabitur porttitor felis non elit lacinia, non condimentum massa eleifend. In ultrices ante sit amet risus ultricies luctus. Ut nec iaculis ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Suspendisse potenti. Vestibulum a volutpat ipsum, vel tincidunt enim.

Cras eu venenatis justo. Nam quis ullamcorper nibh. Etiam imperdiet sagittis est, eu imperdiet arcu pharetra et. Morbi sed mattis diam. Phasellus pharetra lobortis tempus. Suspendisse tellus odio, dapibus vel porta in, pretium et turpis. Pellentesque at metus et risus vestibulum faucibus. In dignissim vestibulum velit non convallis. Nam porta, felis vitae sodales dapibus, diam lacus vestibulum risus, ut cursus sem libero eu nisl. Aliquam ultrices commodo lacus, et suscipit dui luctus vel. Phasellus et ante et mi euismod interdum et eget ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce vitae consequat turpis. Nulla turpis dui, iaculis eget ornare ac, pulvinar nec magna. Nulla purus quam, convallis in pellentesque at, imperdiet nec magna. Ut quam est, posuere in pellentesque lacinia, molestie et mi.

Morbi et ante sagittis, porttitor ante ac, bibendum nisl. Mauris ultrices dui purus, et mollis libero maximus ut. Suspendisse molestie suscipit interdum. Etiam hendrerit velit a tortor pellentesque, at consectetur libero laoreet. Donec eget purus tortor. Donec porttitor eget dolor accumsan ultrices. Sed iaculis magna at euismod pretium. Sed bibendum tortor at rhoncus vehicula. Sed volutpat arcu nec magna tristique, vel laoreet nunc auctor. Nam elementum consectetur ex in ultrices.

Etiam rutrum pretium suscipit. Integer ipsum augue, ornare sit amet justo non, finibus facilisis velit. Donec non tempor nisl. Vestibulum maximus convallis mollis. Ut nec enim a dui maximus scelerisque at ut magna. Maecenas consequat purus nulla, quis suscipit risus dictum ut. Cras eget mauris ut elit laoreet semper eu id diam. Phasellus at felis vitae neque laoreet consectetur nec at erat. Nam erat purus, aliquam nec purus non, vulputate efficitur risus. Quisque consectetur id ligula at mollis. Curabitur non nulla sollicitudin, ultrices lacus ac, blandit lorem. In felis turpis, interdum at finibus eget, volutpat at nibh. Integer non massa justo. Ut at ligula eget nulla sagittis scelerisque ac et ante. Ut lobortis, risus non rhoncus elementum, erat ipsum lobortis risus, vitae dapibus ante urna quis libero.

Vestibulum odio arcu, rutrum nec arcu id, bibendum rhoncus leo. Integer pellentesque nulla a dolor consequat, non mollis dui congue. Quisque finibus ligula urna, a mollis neque suscipit sed. Sed nec egestas purus, eu venenatis libero. Nulla ac ipsum eget libero congue volutpat non at ex. Proin consequat libero id arcu posuere dignissim. Integer pulvinar dictum diam, sit amet viverra velit iaculis id.

Vestibulum faucibus dui a dolor mattis volutpat. Nunc nec aliquet justo, sed sagittis nibh. Pellentesque a nulla non arcu tempor sodales semper vel velit. Maecenas gravida, risus sed fermentum mollis, velit sapien porta augue, id varius urna libero ac tortor. Nulla a magna sit amet lorem sollicitudin aliquam ac eu dolor. Sed dapibus dapibus ipsum accumsan egestas. In rutrum ipsum vitae tellus facilisis lacinia. Nulla facilisi. Vivamus sollicitudin dignissim accumsan. Proin hendrerit, nulla eget feugiat luctus, nulla nisl convallis orci, ac dictum erat magna quis ipsum. Nulla faucibus libero ut pulvinar rhoncus. Nunc ante est, cursus eget mauris non, varius suscipit lorem. Donec vitae nisi placerat, tincidunt tortor nec, tempor ex. Ut malesuada ut orci eget ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis nulla vitae libero scelerisque, non convallis lectus tincidunt.

Curabitur iaculis placerat velit eget ultrices. Donec a commodo velit, sit amet varius sem. Suspendisse eu luctus mauris. Nunc posuere facilisis ex, eu elementum tortor. Curabitur iaculis imperdiet nulla a luctus. Phasellus eu pellentesque elit. Duis mattis ut erat eu maximus. Suspendisse quis augue quis augue volutpat scelerisque et at ante. Mauris risus nunc, pharetra imperdiet vestibulum sit amet, rutrum vel mauris.

Suspendisse porta porta est vitae vehicula. Nulla congue, quam at feugiat semper, dolor neque cursus mi, lacinia consequat felis sapien sit amet elit. Aliquam nibh augue, condimentum at blandit posuere, porta sit amet risus. Ut placerat orci in luctus consequat. Integer dictum erat ac volutpat posuere. Aenean varius molestie cursus. Proin congue nibh maximus varius aliquam. Nunc ut enim nec arcu feugiat bibendum. Nulla id neque facilisis, vestibulum augue quis, pulvinar erat. Donec lacus ligula, ultricies aliquam odio sed, suscipit laoreet urna. Proin at purus vitae nisl lacinia maximus sed at diam.

Curabitur vestibulum ipsum a libero dapibus, eget maximus libero maximus. Vivamus sed nisi ut nisl ornare semper ornare eget sapien. Fusce felis nunc, aliquet facilisis mauris vel, facilisis accumsan sapien. Maecenas luctus varius malesuada. Aliquam erat volutpat. Duis eget diam at enim suscipit condimentum sit amet sed nisl. Pellentesque tristique ante et hendrerit rhoncus. Maecenas sit amet pharetra nibh, at fringilla ipsum. Quisque iaculis vestibulum nibh, eget cursus tellus lobortis pretium. Etiam maximus risus congue lacinia porttitor. Morbi lobortis sit amet orci et suscipit. Aliquam finibus tempus augue, vitae efficitur mauris lobortis et. Phasellus id dapibus enim. Quisque vehicula aliquet facilisis. Praesent dictum ac velit scelerisque interdum.`, { paginate: true, file: { file: fs.readFileSync(__dirname + '/attachment.txt'), name: 'attachement.txt' } });
	}
}

module.exports = VeryLongCommand;
